name: Kat Stevens
theme: jekyll-theme-minimal
title: Kat's blog
description: I'm a Python programmer who works at the Government Digital Service. Expect to hear more details on what music I'm listening to than what code I'm writing.
